title: BOBPE
description: BOt-Based Personalized Education for Productivity Enhancement
author: Bobby Hodgkinson
email: hodgkinr@gmail.com
linkedin_username: bobby-hodgkinson-b6481a24


markdown: kramdown
theme: minima

header_pages:
  - mission.md
  - projects/index.md
  - contact.md